Repository w3c/webappsec-csp, pull requests merged in 2025-04, with the labels that each got.

#722 Fix effective directive for javascript navigation checks
  index.bs
Labels: editorial, clarification

#720 Fix violation's blockedURI for javascript navigations
  index.bs
Labels: clarification

#723 Hash reporting comments from mt
  index.bs
Labels: editorial
